### ISSUE TITLE
Push container images to balena Docker Hub account

### ISSUE THREAD

**Issue by kb2ma** [balena-io-playground/data-relay#59]
Presently I push images to the `kb2ma/cloud-dev` account. There should be an official balena home for these images.

Update reference in `docker-compose.yml`.

**Comment by phil-d-wilson** [comment]
They should be pushed to balenablocks/cloud. I will give you push access to that dockerhub org.

**Comment by kb2ma** [comment]
Pushed to `balenablocks/data-relay`.

Fixed by #83
